In [1]:
import numpy as np
print(np.version)

<module 'numpy.version' from 'c:\\Users\\adwai\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>


In [7]:
# Numpy Arrays

# Shape
# 1D Array
a = np.array([1,2,3,4,5,6])
print(a.shape)

# 2D Array
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

# 3D Array
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.shape)

(6,)
(2, 3)
(2, 2, 2)


In [8]:
# Size
a = np.array([1,2,3,4,5])
print(a.size)

5


In [12]:
# Data type
# Integer Array
a = np.array([1,2,3,4,5])
print(a.dtype)

# Float Array
b = np.array([1.3,2.6,4.7,6.9])
print(b.dtype)

# Complex Array
c = np.array([2+4j,4+7j])
print(c.dtype)

# Boolean Array
d = np.array([True,False])
print(d.dtype)

int32
float64
complex128
bool


In [15]:
# Creating an array with specific data type
a = np.array([1,2,3], dtype = np.float32)
print(a)
print(a.dtype)

b = np.array([4,5,6], dtype=np.int16)
print(b)
print(b.dtype)

[1. 2. 3.]
float32
[4 5 6]
int16


In [37]:
# Some common functions

# np.array()
a = np.array([1,2,3])
print(a)

b = np.array((4,5,6))
print(b)

# np.asarray()
c = [1,2,3,4,5,6]
a = np.asarray(c)
print(a)

d = (12,13,14)
b = np.asarray(d)
print(b)

# np.ones()
a = np.ones(6)
print(a)

b = np.ones((3,3))
print(b)

# np.zeros()
a = np.zeros(5)
print(a)

b = np.zeros((2,3))
print(b)

# np.empty()
a = np.empty(5)
print(a)

b = np.empty((2,3))
print(b)

# np.arange()
a = np.arange(11)
print(a)

b = np.arange(2,11,2)
print(b)

# np.linspace()
a = np.linspace(0,1,5)
print(a)

# np.eye()
a = np.eye(3)
print(a)


[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[12 13 14]
[1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
# Numpy Array Operations and Broadcasting
# Basic array operations

# Addition
a = np.array([1,2,3])
b = np.array([3,4,5])
c = a+b
print(c)

# Subtraction
a = np.array([6,5,4])
b = np.array([1,2,3])
c = a-b
print(c)

# Multiplication
a = np.array([3,6,9])
b = np.array([2,2,2])
c = a*b
print(c)

# Division
a = np.array([3,6,9])
b = np.array([3,3,3])
c = a/b
print(c)

# Scalar Operations
a = np.array([4,6,8])
b = a*2
print(b)
c = a/2
print(c)

# Square root
a = np.array([4,9,16])
b = np.sqrt(a)
print(b)

# Exponential
a = np.array([1,2,3])
b = np.exp(a)
print(b)

[4 6 8]
[5 3 1]
[ 6 12 18]
[1. 2. 3.]
[ 8 12 16]
[2. 3. 4.]
[2. 3. 4.]
[ 2.71828183  7.3890561  20.08553692]


In [47]:
# Broadcasting

# 1D Array and Scalar
a = np.array([1,2,3])
b = 2
c = a+b
print(c)

# 2D Array and 1D Array
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
c = a+b
print(c)

[3 4 5]
[[11 22 33]
 [14 25 36]]
